version: 0.2
phases:
  install:
    commands:
      - echo Entered the install phase...
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - which python
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - python3 helloworld.py
    finally:
      - echo This always runs even if the python command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
